### ISSUE TITLE
feat: New structure of creating connector objects, package extensions, and extra classes

### ISSUE THREAD

**Issue by akselthomsen** [NovoNordisk-OpenSource/connector#11]
Currently each connector class has a twin function to create the connector, and potentially add an extra class.
E.g. the file system class is `Connector_fs` which is created by the `connector_fs()` function:

``` R
connector_fs <- function(path, ..., extra_class = NULL) {
  layer <- Connector_fs$new(path = path, ...)
  if (!is.null(extra_class)) {
    # TODO: not sure about paste and so on
    # extra_class <- paste(class(layer), extra_class, sep = "_")
    class(layer) <- c(extra_class, class(layer))
  }
  return(layer)
}
```

In order to use file system in the yaml configuration file, the type of the connection is specified by the name of the creator function:

``` yaml
connections:
  - con: "adam_fs"
    backend:
        type: "connector_fs"
        path: "{metadata.root_path}/{metadata.trial}/adam"
```

This means that for any extensions to new database types, e.g. databricks, the developer has to implement a creator function, and potentially also a connector class, if they use the same structure.

I propose to use a generic function to create the connector from the yaml file, meaning the additional `connect_xxx()` functions are not needed.
It could look like this, allowing the developer to either use R6 classes or just a function:

``` R
create_layer <- function(connector, ..., extra_class = NULL) {

  # TODO: Some validation of input versus arguments in connector, and extra_class is not used in connector!
  
  if (R6::is.R6(connector)) {
    layer <- connector$new(...)
  } else {
    layer <- connector(...)
  }

  if (!is.null(extra_class)) {
    # TODO: not sure about paste and so on
    # extra_class <- paste(class(layer), extra_class, sep = "_")
    class(layer) <- c(extra_class, class(layer))
  }
  return(layer)
}
```

For the same yaml example as above, the user will now have to point to the class instead:

``` yaml
connections:
  - con: "adam_fs"
    backend:
        type: "Connector_fs"
        path: "{metadata.root_path}/{metadata.trial}/adam"
```

There are several things to consider when choosing:

1. The current separation assigns the responsibility of creating the connections correctly to the developer of any new extension. A change could potentially give us a higher maintainer workload in the future.
2. Separation of creator function and class, with only casing as the difference, can lead to a confusing documentation. See e.g. https://fantastic-adventure-gqozn9k.pages.github.io/dev/10/reference/index.html .
3. By using a generic creator function we ensure that the `extra_class` options is implemented the same way across extensions, which could give a better user experience.
