### ISSUE TITLE
fix: Be able to use {env.examples} without define it

### ISSUE THREAD

**Issue by Cervangirard** [NovoNordisk-OpenSource/connector#28]
today, to be able to use {env.something} then it means that an env part is define inside the yaml.

Example :
```
metadata:
   something: {env.something}

env:
   something: "hej!"
```

but I think it's too restrictive! we should be able to use it without the env part
